//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_host.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bus", Namespace="http://schemas.datacontract.org/2004/07/Online_Bus_Ticket_Booking")]
    [System.SerializableAttribute()]
    public partial class Bus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Arrival_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Bus_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Dept_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Arrival_time {
            get {
                return this.Arrival_timeField;
            }
            set {
                if ((this.Arrival_timeField.Equals(value) != true)) {
                    this.Arrival_timeField = value;
                    this.RaisePropertyChanged("Arrival_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bus_no {
            get {
                return this.Bus_noField;
            }
            set {
                if ((this.Bus_noField.Equals(value) != true)) {
                    this.Bus_noField = value;
                    this.RaisePropertyChanged("Bus_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dept_time {
            get {
                return this.Dept_timeField;
            }
            set {
                if ((this.Dept_timeField.Equals(value) != true)) {
                    this.Dept_timeField = value;
                    this.RaisePropertyChanged("Dept_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ticket", Namespace="http://schemas.datacontract.org/2004/07/Online_Bus_Ticket_Booking")]
    [System.SerializableAttribute()]
    public partial class Ticket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Arrival_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_toField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Dept_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Seat_numField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Total_seatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Arrival_time {
            get {
                return this.Arrival_timeField;
            }
            set {
                if ((this.Arrival_timeField.Equals(value) != true)) {
                    this.Arrival_timeField = value;
                    this.RaisePropertyChanged("Arrival_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_from {
            get {
                return this.C_fromField;
            }
            set {
                if ((object.ReferenceEquals(this.C_fromField, value) != true)) {
                    this.C_fromField = value;
                    this.RaisePropertyChanged("C_from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_name {
            get {
                return this.C_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.C_nameField, value) != true)) {
                    this.C_nameField = value;
                    this.RaisePropertyChanged("C_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_to {
            get {
                return this.C_toField;
            }
            set {
                if ((object.ReferenceEquals(this.C_toField, value) != true)) {
                    this.C_toField = value;
                    this.RaisePropertyChanged("C_to");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dept_time {
            get {
                return this.Dept_timeField;
            }
            set {
                if ((this.Dept_timeField.Equals(value) != true)) {
                    this.Dept_timeField = value;
                    this.RaisePropertyChanged("Dept_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone_no {
            get {
                return this.Phone_noField;
            }
            set {
                if ((object.ReferenceEquals(this.Phone_noField, value) != true)) {
                    this.Phone_noField = value;
                    this.RaisePropertyChanged("Phone_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seat_num {
            get {
                return this.Seat_numField;
            }
            set {
                if ((object.ReferenceEquals(this.Seat_numField, value) != true)) {
                    this.Seat_numField = value;
                    this.RaisePropertyChanged("Seat_num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total_seat {
            get {
                return this.Total_seatField;
            }
            set {
                if ((this.Total_seatField.Equals(value) != true)) {
                    this.Total_seatField = value;
                    this.RaisePropertyChanged("Total_seat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/Online_Bus_Ticket_Booking")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Card_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CvvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Card_no {
            get {
                return this.Card_noField;
            }
            set {
                if ((this.Card_noField.Equals(value) != true)) {
                    this.Card_noField = value;
                    this.RaisePropertyChanged("Card_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cvv {
            get {
                return this.CvvField;
            }
            set {
                if ((this.CvvField.Equals(value) != true)) {
                    this.CvvField = value;
                    this.RaisePropertyChanged("Cvv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBus", ReplyAction="http://tempuri.org/IService1/AddBusResponse")]
        bool AddBus(Bus_host.ServiceReference1.Bus b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBus", ReplyAction="http://tempuri.org/IService1/AddBusResponse")]
        System.Threading.Tasks.Task<bool> AddBusAsync(Bus_host.ServiceReference1.Bus b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBus", ReplyAction="http://tempuri.org/IService1/UpdateBusResponse")]
        Bus_host.ServiceReference1.Bus UpdateBus(Bus_host.ServiceReference1.Bus b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBus", ReplyAction="http://tempuri.org/IService1/UpdateBusResponse")]
        System.Threading.Tasks.Task<Bus_host.ServiceReference1.Bus> UpdateBusAsync(Bus_host.ServiceReference1.Bus b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBus", ReplyAction="http://tempuri.org/IService1/DeleteBusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Online_Bus_Ticket_Booking.NotFoundFolt), Action="http://tempuri.org/IService1/DeleteBusNotFoundFoltFault", Name="NotFoundFolt", Namespace="http://schemas.datacontract.org/2004/07/Online_Bus_Ticket_Booking")]
        bool DeleteBus(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBus", ReplyAction="http://tempuri.org/IService1/DeleteBusResponse")]
        System.Threading.Tasks.Task<bool> DeleteBusAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBus", ReplyAction="http://tempuri.org/IService1/GetBusResponse")]
        Bus_host.ServiceReference1.Bus GetBus(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBus", ReplyAction="http://tempuri.org/IService1/GetBusResponse")]
        System.Threading.Tasks.Task<Bus_host.ServiceReference1.Bus> GetBusAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBus", ReplyAction="http://tempuri.org/IService1/GetAllBusResponse")]
        System.Data.DataSet GetAllBus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBus", ReplyAction="http://tempuri.org/IService1/GetAllBusResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllBusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTicket", ReplyAction="http://tempuri.org/IService1/AddTicketResponse")]
        bool AddTicket(Bus_host.ServiceReference1.Ticket t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTicket", ReplyAction="http://tempuri.org/IService1/AddTicketResponse")]
        System.Threading.Tasks.Task<bool> AddTicketAsync(Bus_host.ServiceReference1.Ticket t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTicket", ReplyAction="http://tempuri.org/IService1/UpdateTicketResponse")]
        Bus_host.ServiceReference1.Ticket UpdateTicket(Bus_host.ServiceReference1.Ticket t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTicket", ReplyAction="http://tempuri.org/IService1/UpdateTicketResponse")]
        System.Threading.Tasks.Task<Bus_host.ServiceReference1.Ticket> UpdateTicketAsync(Bus_host.ServiceReference1.Ticket t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTicket", ReplyAction="http://tempuri.org/IService1/DeleteTicketResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Online_Bus_Ticket_Booking.NotFoundFolt), Action="http://tempuri.org/IService1/DeleteTicketNotFoundFoltFault", Name="NotFoundFolt", Namespace="http://schemas.datacontract.org/2004/07/Online_Bus_Ticket_Booking")]
        bool DeleteTicket(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTicket", ReplyAction="http://tempuri.org/IService1/DeleteTicketResponse")]
        System.Threading.Tasks.Task<bool> DeleteTicketAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTicket", ReplyAction="http://tempuri.org/IService1/GetTicketResponse")]
        Bus_host.ServiceReference1.Ticket GetTicket(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTicket", ReplyAction="http://tempuri.org/IService1/GetTicketResponse")]
        System.Threading.Tasks.Task<Bus_host.ServiceReference1.Ticket> GetTicketAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTicket", ReplyAction="http://tempuri.org/IService1/GetAllTicketResponse")]
        System.Data.DataSet GetAllTicket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTicket", ReplyAction="http://tempuri.org/IService1/GetAllTicketResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllTicketAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustTicket", ReplyAction="http://tempuri.org/IService1/GetCustTicketResponse")]
        System.Data.DataSet GetCustTicket(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustTicket", ReplyAction="http://tempuri.org/IService1/GetCustTicketResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCustTicketAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPayment", ReplyAction="http://tempuri.org/IService1/AddPaymentResponse")]
        bool AddPayment(Bus_host.ServiceReference1.Payment p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPayment", ReplyAction="http://tempuri.org/IService1/AddPaymentResponse")]
        System.Threading.Tasks.Task<bool> AddPaymentAsync(Bus_host.ServiceReference1.Payment p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Bus_host.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Bus_host.ServiceReference1.IService1>, Bus_host.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddBus(Bus_host.ServiceReference1.Bus b) {
            return base.Channel.AddBus(b);
        }
        
        public System.Threading.Tasks.Task<bool> AddBusAsync(Bus_host.ServiceReference1.Bus b) {
            return base.Channel.AddBusAsync(b);
        }
        
        public Bus_host.ServiceReference1.Bus UpdateBus(Bus_host.ServiceReference1.Bus b) {
            return base.Channel.UpdateBus(b);
        }
        
        public System.Threading.Tasks.Task<Bus_host.ServiceReference1.Bus> UpdateBusAsync(Bus_host.ServiceReference1.Bus b) {
            return base.Channel.UpdateBusAsync(b);
        }
        
        public bool DeleteBus(int id) {
            return base.Channel.DeleteBus(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBusAsync(int id) {
            return base.Channel.DeleteBusAsync(id);
        }
        
        public Bus_host.ServiceReference1.Bus GetBus(int id) {
            return base.Channel.GetBus(id);
        }
        
        public System.Threading.Tasks.Task<Bus_host.ServiceReference1.Bus> GetBusAsync(int id) {
            return base.Channel.GetBusAsync(id);
        }
        
        public System.Data.DataSet GetAllBus() {
            return base.Channel.GetAllBus();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllBusAsync() {
            return base.Channel.GetAllBusAsync();
        }
        
        public bool AddTicket(Bus_host.ServiceReference1.Ticket t) {
            return base.Channel.AddTicket(t);
        }
        
        public System.Threading.Tasks.Task<bool> AddTicketAsync(Bus_host.ServiceReference1.Ticket t) {
            return base.Channel.AddTicketAsync(t);
        }
        
        public Bus_host.ServiceReference1.Ticket UpdateTicket(Bus_host.ServiceReference1.Ticket t) {
            return base.Channel.UpdateTicket(t);
        }
        
        public System.Threading.Tasks.Task<Bus_host.ServiceReference1.Ticket> UpdateTicketAsync(Bus_host.ServiceReference1.Ticket t) {
            return base.Channel.UpdateTicketAsync(t);
        }
        
        public bool DeleteTicket(int id) {
            return base.Channel.DeleteTicket(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTicketAsync(int id) {
            return base.Channel.DeleteTicketAsync(id);
        }
        
        public Bus_host.ServiceReference1.Ticket GetTicket(int id) {
            return base.Channel.GetTicket(id);
        }
        
        public System.Threading.Tasks.Task<Bus_host.ServiceReference1.Ticket> GetTicketAsync(int id) {
            return base.Channel.GetTicketAsync(id);
        }
        
        public System.Data.DataSet GetAllTicket() {
            return base.Channel.GetAllTicket();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllTicketAsync() {
            return base.Channel.GetAllTicketAsync();
        }
        
        public System.Data.DataSet GetCustTicket(string email) {
            return base.Channel.GetCustTicket(email);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCustTicketAsync(string email) {
            return base.Channel.GetCustTicketAsync(email);
        }
        
        public bool AddPayment(Bus_host.ServiceReference1.Payment p) {
            return base.Channel.AddPayment(p);
        }
        
        public System.Threading.Tasks.Task<bool> AddPaymentAsync(Bus_host.ServiceReference1.Payment p) {
            return base.Channel.AddPaymentAsync(p);
        }
    }
}
